### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by rslruiz** [jayycrl/py3ArthemisProject#3]
Prepare a hierarchy chart [Gaddis, p.143].

**Comment by ghost** [comment]
A function hierarchy chart has been added to the README file: https://github.com/jayycrl/py3ArthemisProject#readme.

**Comment by rslruiz** [comment]
Remove the hierarchy chart from README.md. Upload it as another file.

**Comment by ghost** [comment]
Hierarchy chart was added as part of the final documentation release here: https://github.com/jayycrl/py3ArthemisProject/releases/tag/final-documentation
